sudo: required
services:
    - docker

before_install:
    - docker build -t batuhanertas/docker-react -f Dockerfile.dev .

script:
    - docker run batuhanertas/docker-react npm run test -- --coverage